model_name: wnet_smartcrop_lpis_gt_1 # This is the name for the model
data_source: !!python/object/apply:hugin.io.FileSystemLoader
  kwds:
    data_pattern: '(?P<region>T[0-9A-Z]+)_(?P<timestamp>[A-Z0-9]+)_(?P<type>[A-Z0-9_a-z]+)_(?P<res>[0-9a-z]+)_(?P<crs>[0-9]+)..*$'
    id_format: '{region}-{timestamp}'
    type_format: '{type}-{res}-{crs}'
    input_source: ../data/sentinel2_bands_only_olanda_2018/
    validation_percent: 0.2
dataset_cache: /home/tardis/test_smartcrop_hugin/etc/samples/sample_olanda_04_05_06_07_08_09.yaml
window_size: [ 256, 256 ]
stride_size: 128
random_seed: 42
mapping:
  inputs:
      - [ "B02-10m-4326", 1 ]
      - [ "B03-10m-4326", 1 ]
      - [ "B04-10m-4326", 1 ]
      - [ "B08-10m-4326", 1]
  target:
      - [ "GTLPISNODATA-10m-4326", 1 ]
model_type: keras
model:
  model_builder: hugin.models.wnet:build_wnet
  options:
    n_channels: 4
    nr_classes: 25
  batch_size: 5
  prefetch_queue_size: 10 # Default 10
  model_path: "../data/smartcrop-models/models/{model_name}/{hostname}-{user}.hdf5"
  loss: categorical_crossentropy
  load_only_weights: False
  log: "../data/smartcrop-models/models/{model_name}/logging-{model_name}-{hostname}.csv"
  adaptive_lr:
    monitor: val_loss
    factor: !!float 0.1
    patience: 3
    verbose: 1
    epsilon: !!float 1e-4
    mode: min
  checkpoint:
    path: "../data/smartcrop-models/models/_checkpoints/%(model_name)s/%(hostname)s-%(user)s-{epoch:02d}.hdf5"
    options: # This is optional
       save_best_only: False
  early_stopping:
    monitor: val_loss
    patience: 15
    verbose: 0
    mode: auto
  train_epochs: 300
  swap_axes: True
  optimiser: !!python/object/apply:keras.optimizers.Adam
    kwds:
      lr: !!float 0.0001
      beta_1: !!float 0.9
      beta_2: !!float 0.999
      epsilon: !!float 1e-8
  metrics:
    - accuracy
    - !!python/name:hugin.tools.utils.dice_coef
  jaccard_coef: False
  format_converter: !!python/object/apply:hugin.io.CategoricalConverter
    kwds:
      num_classes: 25
  z_scaler:
    B02-10m-4326:
      mean: 327.22765374622156
      std: 465.1138674711807
    B03-10m-4326:
      mean: 474.0944328027927
      std: 535.5880716696187
    B04-10m-4326:
      mean: 440.85761188762257
      std: 613.4453541367335
    B08-10m-4326:
      mean: 1721.9533453136391
      std: 1745.8926887148723


