version: 1
formatters:
  brief:
    format: '%(message)s'
  default:
    format: "%(asctime)s %(filename)12s:%(lineno)d\t%(levelname)-8s %(name)-18s %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    level   : DEBUG
    stream  : ext://sys.stderr
loggers:
  hugin:
    handlers: [console, ]
    level: DEBUG
